
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 19;
  public static final int cerouno = 12;
  public static final int ceromas = 10;
  public static final int end = 6;
  public static final int coma = 15;
  public static final int conj = 2;
  public static final int charas = 16;
  public static final int conc = 11;
  public static final int separate = 5;
  public static final int open = 7;
  public static final int EOF = 0;
  public static final int esp = 17;
  public static final int palabra = 18;
  public static final int unomas = 9;
  public static final int assign = 4;
  public static final int error = 1;
  public static final int fromto = 14;
  public static final int clos = 8;
  public static final int detail = 3;
  public static final int estot = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "conj",
  "detail",
  "assign",
  "separate",
  "end",
  "open",
  "clos",
  "unomas",
  "ceromas",
  "conc",
  "cerouno",
  "estot",
  "fromto",
  "coma",
  "charas",
  "esp",
  "palabra",
  "cadena"
  };
}

