
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int palabra = 9;
  public static final int tld = 3;
  public static final int end = 7;
  public static final int conj = 2;
  public static final int EOF = 0;
  public static final int detail = 4;
  public static final int entero = 8;
  public static final int separate = 6;
  public static final int error = 1;
  public static final int assign = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "conj",
  "tld",
  "detail",
  "assign",
  "separate",
  "end",
  "entero",
  "palabra"
  };
}

